/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package explorebatucity.ui;

import explorebatucity.kelas.loginout;
import javax.swing.*;

/**
 *
 * @author Zidan
 */
public class RuangAdminUtama extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public RuangAdminUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tombolkuliner = new javax.swing.JButton();
        tombollogout = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tombolsekolah = new javax.swing.JButton();
        tombolpariwisata = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Explore Batu City");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(350, 110));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(46, 204, 113));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tombolkuliner.setBackground(new java.awt.Color(255, 255, 255));
        tombolkuliner.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tombolkuliner.setForeground(new java.awt.Color(51, 51, 51));
        tombolkuliner.setText("Kuliner");
        tombolkuliner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolkuliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolkulinerActionPerformed(evt);
            }
        });
        jPanel2.add(tombolkuliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 150, 50));

        tombollogout.setBackground(new java.awt.Color(231, 76, 60));
        tombollogout.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tombollogout.setText("Logout");
        tombollogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombollogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombollogoutActionPerformed(evt);
            }
        });
        jPanel2.add(tombollogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 190, 40));

        jLabel12.setFont(new java.awt.Font("Minecraftia", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Masuk ke Halaman admin");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        tombolsekolah.setBackground(new java.awt.Color(255, 255, 255));
        tombolsekolah.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tombolsekolah.setForeground(new java.awt.Color(51, 51, 51));
        tombolsekolah.setText("Sekolah");
        tombolsekolah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolsekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolsekolahActionPerformed(evt);
            }
        });
        jPanel2.add(tombolsekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 150, 50));

        tombolpariwisata.setBackground(new java.awt.Color(255, 255, 255));
        tombolpariwisata.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tombolpariwisata.setForeground(new java.awt.Color(51, 51, 51));
        tombolpariwisata.setText("Pariwisata");
        tombolpariwisata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolpariwisata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolpariwisataActionPerformed(evt);
            }
        });
        jPanel2.add(tombolpariwisata, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 150, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 420, 390));

        jPanel3.setBackground(new java.awt.Color(39, 174, 96));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(39, 174, 96));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(7);
        jTextArea1.setText("Kota Batu adalah sebuah kota\ndi Provinsi Jawa Timur, Indonesia. \nKota Batu dahulu merupakan \nbagian dari Kabupaten Malang, \nyang kemudian ditetapkan \nmenjadi kota administratif pada 6 Maret 1993. \nPada tanggal 17 Oktober 2001, \nBatu ditetapkan sebagai kota otonom \nyang terpisah dari Kabupaten Malang. \nBatu dikenal sebagai salah satu \nkota wisata terkemuka di Indonesia karena \npotensi keindahan alam yang luar biasa.\nKekaguman bangsa Belanda terhadap \nkeindahan dan keelokan alam Batu \nmembuat wilayah kota Batu disejajarkan \ndengan sebuah negara di Eropa yaitu \nSwiss dan dijuluki sebagai \nDe Kleine Zwitserland atau Swiss Kecil \ndi Pulau Jawa.");
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(39, 174, 96));
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jTextArea1.setSelectionColor(new java.awt.Color(39, 174, 96));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 290, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\File Programming\\Semester 2\\Tugas Prak PBO\\netbeans\\7. Project UAS\\explorebatucity\\src\\explorebatucity\\icon\\Untitled-1.png")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 100, 110));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 310, 450));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Minecraftia", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Halaman Admin Utama");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 7, 220, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void keluar() {
        loginout[] out = new loginout[1];
        
        out[0]= new loginout();
        
        out[0].setKeluar("Yakin ingin Keluar?");
        
        int opsi = JOptionPane.showConfirmDialog(null, out[0].getKeluar(), "LogOut", JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION) {
            this.dispose();
            new Login().setVisible(true);
        } else if (opsi == JOptionPane.NO_OPTION) {
        }
    }
    private void tombollogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombollogoutActionPerformed
        // TODO add your handling code here:
        keluar();
    }//GEN-LAST:event_tombollogoutActionPerformed

    private void tombolkulinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolkulinerActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new RuangAdminKuliner().setVisible(true);
    }//GEN-LAST:event_tombolkulinerActionPerformed

    private void tombolsekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolsekolahActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new RuangAdminSekolah().setVisible(true);
    }//GEN-LAST:event_tombolsekolahActionPerformed

    private void tombolpariwisataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolpariwisataActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new RuangAdminPariwisata().setVisible(true);
    }//GEN-LAST:event_tombolpariwisataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Flatlaf Dark".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RuangAdminUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RuangAdminUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RuangAdminUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RuangAdminUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RuangAdminUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton tombolkuliner;
    private javax.swing.JButton tombollogout;
    private javax.swing.JButton tombolpariwisata;
    private javax.swing.JButton tombolsekolah;
    // End of variables declaration//GEN-END:variables
}
