/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package explorebatucity.ui;

import explorebatucity.kelas.loginout;
import javax.swing.JOptionPane;

/**
 *
 * @author Zidan
 */
public class SignUp extends javax.swing.JFrame {

    loginout app = new loginout();

    /**
     * Creates new form Log_in
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tombolcreate = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();
        txtusername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelkelogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Explore Batu City");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(350, 80));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(46, 204, 113));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(39, 174, 96));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 790, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtemail.setBackground(new java.awt.Color(255, 255, 255));
        txtemail.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtemail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel3.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 280, 30));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Username");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Password");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 30));

        tombolcreate.setBackground(new java.awt.Color(76, 209, 55));
        tombolcreate.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        tombolcreate.setForeground(new java.awt.Color(0, 0, 0));
        tombolcreate.setText("Create");
        tombolcreate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tombolcreate.setBorderPainted(false);
        tombolcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolcreateActionPerformed(evt);
            }
        });
        jPanel3.add(tombolcreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 370, 30));

        txtpassword.setBackground(new java.awt.Color(255, 255, 255));
        txtpassword.setFont(new java.awt.Font("Anonymous Pro", 0, 18)); // NOI18N
        txtpassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel3.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 280, 30));

        txtusername.setBackground(new java.awt.Color(255, 255, 255));
        txtusername.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtusername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel3.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 280, 30));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("E-mail");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 30));

        jLabel8.setFont(new java.awt.Font("Minecraftia", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Explore Batu City");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 190, 40));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 2, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Sign up to see about Batu City");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 190, 20));

        labelkelogin.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        labelkelogin.setForeground(new java.awt.Color(0, 0, 0));
        labelkelogin.setText("Login now");
        labelkelogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelkelogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelkeloginMouseClicked(evt);
            }
        });
        jPanel3.add(labelkelogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 70, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 2, 14)); // NOI18N
        jLabel3.setText("Have an account?");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 110, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 410, 340));

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\File Programming\\Semester 2\\Tugas Prak PBO\\netbeans\\7. Project UAS\\explorebatucity\\src\\explorebatucity\\icon\\apple.png")); // NOI18N
        jLabel11.setText("jLabel6");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 480, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelkeloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelkeloginMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_labelkeloginMouseClicked

    private void tombolcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolcreateActionPerformed
        // TODO add your handling code here:
        try {
            app.setEmail(txtemail.getText());
            app.setUserid(txtusername.getText());
            app.setPass(txtpassword.getText());

            app.simpandata(
                    app.getEmail(),
                    app.getUserid(),
                    app.getPass());
            JOptionPane.showMessageDialog(null, "Berhasil Registrasi");
            txtemail.setText("");
            txtusername.setText("");
            txtpassword.setText("");
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Gagal Registrasi");
        }
    }//GEN-LAST:event_tombolcreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Flatlaf Dark".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelkelogin;
    private javax.swing.JButton tombolcreate;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
