package explorebatucity.ui;

import explorebatucity.DB.koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zidan
 */
public class ui_Pariwisata extends javax.swing.JFrame {

    /**
     * Creates new form Log_in
     */
    public ui_Pariwisata() {
        initComponents();
        tampil_combo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox<>();
        TombolMenuUtama = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnamatempat = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtinfo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtkeunikan = new javax.swing.JTextArea();
        txtnotelp = new javax.swing.JTextField();
        txtjambuka = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Explore Batu City");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(250, 80));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(46, 204, 113));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Silahkan pilih tempat wisata");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 40));

        ComboBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });
        jPanel3.add(ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 210, 40));

        TombolMenuUtama.setBackground(new java.awt.Color(231, 76, 60));
        TombolMenuUtama.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        TombolMenuUtama.setForeground(new java.awt.Color(255, 255, 255));
        TombolMenuUtama.setText("Kembali ke Menu Utama");
        TombolMenuUtama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TombolMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolMenuUtamaActionPerformed(evt);
            }
        });
        jPanel3.add(TombolMenuUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 190, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, 490));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Keunikan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        txtnamatempat.setEditable(false);
        txtnamatempat.setBackground(new java.awt.Color(46, 204, 113));
        txtnamatempat.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtnamatempat.setForeground(new java.awt.Color(255, 255, 255));
        txtnamatempat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnamatempat.setBorder(null);
        jPanel1.add(txtnamatempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 230, 30));

        txtalamat.setEditable(false);
        txtalamat.setBackground(new java.awt.Color(46, 204, 113));
        txtalamat.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtalamat.setForeground(new java.awt.Color(255, 255, 255));
        txtalamat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtalamat.setBorder(null);
        jPanel1.add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 600, 20));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Deskripsi");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Alamat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Buka");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telepon");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jScrollPane1.setBorder(null);

        txtinfo.setEditable(false);
        txtinfo.setBackground(new java.awt.Color(46, 204, 113));
        txtinfo.setColumns(20);
        txtinfo.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtinfo.setForeground(new java.awt.Color(255, 255, 255));
        txtinfo.setRows(5);
        txtinfo.setTabSize(5);
        txtinfo.setBorder(null);
        txtinfo.setCaretColor(new java.awt.Color(39, 174, 96));
        txtinfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtinfo.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtinfo.setSelectionColor(new java.awt.Color(39, 174, 96));
        jScrollPane1.setViewportView(txtinfo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 600, 100));

        jScrollPane2.setBorder(null);

        txtkeunikan.setEditable(false);
        txtkeunikan.setBackground(new java.awt.Color(46, 204, 113));
        txtkeunikan.setColumns(20);
        txtkeunikan.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtkeunikan.setForeground(new java.awt.Color(255, 255, 255));
        txtkeunikan.setRows(5);
        txtkeunikan.setTabSize(5);
        txtkeunikan.setBorder(null);
        txtkeunikan.setCaretColor(new java.awt.Color(39, 174, 96));
        txtkeunikan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtkeunikan.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtkeunikan.setSelectionColor(new java.awt.Color(39, 174, 96));
        jScrollPane2.setViewportView(txtkeunikan);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 600, 100));

        txtnotelp.setEditable(false);
        txtnotelp.setBackground(new java.awt.Color(46, 204, 113));
        txtnotelp.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtnotelp.setForeground(new java.awt.Color(255, 255, 255));
        txtnotelp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnotelp.setBorder(null);
        jPanel1.add(txtnotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 600, 20));

        txtjambuka.setEditable(false);
        txtjambuka.setBackground(new java.awt.Color(46, 204, 113));
        txtjambuka.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtjambuka.setForeground(new java.awt.Color(255, 255, 255));
        txtjambuka.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjambuka.setBorder(null);
        jPanel1.add(txtjambuka, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 600, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 760, 550));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Minecraftia", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pariwisata ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tampil_combo() {
        try {
        Connection con = koneksi.koneksiDB();
        Statement stt = con.createStatement();
        String sql = "select namatempat from pariwisata order by namatempat asc";      
        ResultSet res = stt.executeQuery(sql);                                
        ComboBox.addItem("");
       
        while(res.next()){
            Object[] halo = new Object[1];
            halo[0] = res.getString(1);
            
            ComboBox.addItem((String) halo[0]);                                      
        }
        res.close(); stt.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void tampilcb() {
        try {
        Connection con = koneksi.koneksiDB();
        Statement stt = con.createStatement();
        String sql = "select namatempat, info, alamat, jambuka, notelp, keunikan from pariwisata where namatempat='"
                +ComboBox.getSelectedItem()+"'";  
        ResultSet res = stt.executeQuery(sql);
        
        while(res.next()){
            Object[] ob = new Object[6];
            ob[0]= res.getString(1);
            ob[1]= res.getString(2);
            ob[2]= res.getString(3);
            ob[3]= res.getString(4);
            ob[4]= res.getString(5);
            ob[5]= res.getString(6);
            
            txtnamatempat.setText((String) ob[0]);
            txtinfo.setText((String) ob[1]);
            txtalamat.setText((String) ob[2]);
            txtjambuka.setText((String) ob[3]);
            txtnotelp.setText((String) ob[4]);
            txtkeunikan.setText((String) ob[5]);
        }
        res.close(); stt.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }              
    }
    
    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        // TODO add your handling code here:
        tampilcb();
    }//GEN-LAST:event_ComboBoxActionPerformed

    private void TombolMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolMenuUtamaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new explorebatucity.ui.Menu().setVisible(true);
    }//GEN-LAST:event_TombolMenuUtamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Flatlaf Dark".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ui_Pariwisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ui_Pariwisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ui_Pariwisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ui_Pariwisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ui_Pariwisata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton TombolMenuUtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextArea txtinfo;
    private javax.swing.JTextField txtjambuka;
    private javax.swing.JTextArea txtkeunikan;
    private javax.swing.JTextField txtnamatempat;
    private javax.swing.JTextField txtnotelp;
    // End of variables declaration//GEN-END:variables
}
